server:
  port: 9098    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    fetch-registry: true

spring:
  application:
    name: bonus-service    #service name
  data:
    mongodb:
      uri: mongodb://localhost:27017/bonusDB
  cloud:
    stream:
      bindings:
        output:
          destination: overtimes
logging:
  level:
    com.derzhavets: DEBUG